### ISSUE TITLE
Relevant Level and Question Seeds

### ISSUE THREAD

**Issue by reptile18** [erin-smith/Achilles-heel#55]
We need three levels: Medusa's Lair, Hydra's Sea Cave, and Hades Den.

And need 12 questions for each of those levels.

**Comment by reptile18** [comment]
Or a "Monster" level with a Medusa category, a Hydra category, etc.

And then a Gods level or then something else...

and an underworld level with underworld questions?
-------------------------------------------------------------------------------
Or Medusa with Gorgon questions???
-------------------------------------------------------------------------------

**Comment by erin-smith** [comment]
We have One Hades(Underworld pertaining) level with 12 monster questions.  (4 hydra, 4 chimera, 4 underworld monsters) ;-)
